import type { Subject } from "@/lib/types";

/**
 * Striver's A2Z DSA Sheet — full 18-step curriculum.
 * Item format: "Name"  OR  ["Name", "Easy|Medium|Hard"]
 *
 * Source: takeuforward.org (Striver's A2Z DSA Sheet).
 */
const searchFn = (name: string, sectionName?: string) =>
  `/api/dsa-resource?title=${encodeURIComponent(name)}&section=${encodeURIComponent(sectionName || "")}`;

export const dsaTrack: Subject = {
  id: "dsa",
  name: "Striver A2Z DSA Sheet",
  short: "DSA",
  color: "#f59e0b",
  kind: "dsa",
  desc: "455+ problems across 18 steps — from basics to advanced graphs & DP.",
  source: "takeuforward.org",
  search: searchFn,
  _total: 0,
  sections: [
    { name: "Step 1 · Learn the Basics", items: [
      "User Input / Output", "Data Types", "If-Else statements", "Switch Statement",
      "Arrays, Strings basics", "For loops", "While loops", "Functions (pass by ref & value)",
      "Time & Space Complexity",
      ["Print patterns (1-22)", "Easy"],
      ["Count digits of a number", "Easy"], ["Reverse a number", "Easy"],
      ["Check palindrome number", "Easy"], ["GCD or HCF", "Easy"],
      ["Armstrong number", "Easy"], ["Print all divisors", "Easy"], ["Check prime", "Easy"],
      ["Recursion: print name N times", "Easy"], ["Print 1 to N (recursion)", "Easy"],
      ["Print N to 1 (recursion)", "Easy"], ["Sum of first N numbers", "Easy"],
      ["Factorial (recursion)", "Easy"], ["Reverse an array (recursion)", "Easy"],
      ["Check palindrome string (recursion)", "Easy"], ["Fibonacci number (recursion)", "Easy"],
      ["Count frequencies of elements (hashing)", "Easy"],
      ["Highest & lowest frequency element", "Easy"],
    ]},
    { name: "Step 2 · Sorting Techniques", items: [
      ["Selection Sort", "Easy"], ["Bubble Sort", "Easy"], ["Insertion Sort", "Easy"],
      ["Merge Sort", "Medium"], ["Recursive Bubble Sort", "Easy"],
      ["Recursive Insertion Sort", "Easy"], ["Quick Sort", "Medium"],
    ]},
    { name: "Step 3 · Arrays", items: [
      ["Largest element in array", "Easy"], ["Second largest element", "Easy"],
      ["Check if array is sorted", "Easy"], ["Remove duplicates from sorted array", "Easy"],
      ["Left rotate array by one", "Easy"], ["Left rotate array by D places", "Easy"],
      ["Move zeros to end", "Easy"], ["Linear search", "Easy"],
      ["Union of two sorted arrays", "Easy"], ["Find missing number", "Easy"],
      ["Max consecutive ones", "Easy"], ["Single number (find unique)", "Easy"],
      ["Longest subarray with sum K (positives)", "Medium"],
      ["Longest subarray with sum K (pos+neg)", "Medium"],
      ["Two Sum problem", "Medium"], ["Sort 0s, 1s and 2s (DNF)", "Medium"],
      ["Majority element (>n/2)", "Medium"], ["Kadane's Algorithm (max subarray sum)", "Medium"],
      ["Print subarray with max sum", "Medium"], ["Stock Buy and Sell", "Medium"],
      ["Rearrange array by sign", "Medium"], ["Next Permutation", "Medium"],
      ["Leaders in an array", "Medium"], ["Longest consecutive sequence", "Medium"],
      ["Set matrix zeros", "Medium"], ["Rotate matrix by 90 degrees", "Medium"],
      ["Spiral traversal of matrix", "Medium"], ["Count subarrays with sum K", "Medium"],
      ["Pascal's triangle", "Hard"], ["Majority element (>n/3)", "Hard"],
      ["3 Sum problem", "Hard"], ["4 Sum problem", "Hard"],
      ["Largest subarray with 0 sum", "Hard"], ["Count subarrays with XOR = K", "Hard"],
      ["Merge overlapping intervals", "Hard"], ["Merge two sorted arrays (no extra space)", "Hard"],
      ["Find repeating and missing number", "Hard"], ["Count inversions", "Hard"],
      ["Reverse pairs", "Hard"], ["Maximum product subarray", "Hard"],
    ]},
    { name: "Step 4 · Binary Search", items: [
      ["Binary search to find X", "Easy"], ["Lower bound", "Easy"], ["Upper bound", "Easy"],
      ["Search insert position", "Easy"], ["Floor and Ceil in sorted array", "Easy"],
      ["First & last occurrence", "Easy"], ["Count occurrences", "Easy"],
      ["Search in rotated sorted array I", "Medium"], ["Search in rotated sorted array II", "Medium"],
      ["Minimum in rotated sorted array", "Medium"], ["Find rotation count", "Medium"],
      ["Single element in sorted array", "Medium"], ["Find peak element", "Medium"],
      ["Square root using BS", "Medium"], ["Nth root of a number", "Medium"],
      ["Koko eating bananas", "Medium"], ["Min days to make M bouquets", "Medium"],
      ["Smallest divisor given threshold", "Medium"], ["Capacity to ship packages in D days", "Medium"],
      ["Kth missing positive number", "Medium"], ["Aggressive cows", "Hard"],
      ["Book allocation problem", "Hard"], ["Split array - largest sum", "Hard"],
      ["Painter's partition", "Hard"], ["Median of two sorted arrays", "Hard"],
      ["Kth element of two sorted arrays", "Hard"],
      ["Row with maximum 1s", "Easy"], ["Search in a 2D matrix", "Medium"],
      ["Search in 2D matrix II", "Medium"], ["Peak element in 2D matrix", "Hard"],
      ["Median in row-wise sorted matrix", "Hard"],
    ]},
    { name: "Step 5 · Strings", items: [
      ["Remove outermost parentheses", "Easy"], ["Reverse words in a string", "Easy"],
      ["Largest odd number in string", "Easy"], ["Longest common prefix", "Easy"],
      ["Isomorphic strings", "Easy"], ["Check rotation of string", "Easy"],
      ["Check anagram", "Easy"], ["Sort characters by frequency", "Medium"],
      ["Maximum nesting depth of parentheses", "Medium"], ["Roman to integer", "Medium"],
      ["Implement Atoi", "Medium"], ["Count number of substrings", "Medium"],
      ["Longest palindromic substring", "Hard"], ["Sum of beauty of all substrings", "Hard"],
      ["Reverse every word", "Medium"],
    ]},
    { name: "Step 6 · Linked List", items: [
      ["Introduction to LinkedList", "Easy"], ["Insert a node in LinkedList", "Easy"],
      ["Delete a node in LinkedList", "Easy"], ["Find length of LinkedList", "Easy"],
      ["Search an element in LinkedList", "Easy"],
      ["Introduction to Doubly LinkedList", "Easy"], ["Insert in DLL", "Easy"],
      ["Delete in DLL", "Easy"], ["Reverse a DLL", "Medium"],
      ["Middle of LinkedList (tortoise-hare)", "Easy"], ["Reverse LinkedList (iterative)", "Easy"],
      ["Reverse LinkedList (recursive)", "Medium"], ["Detect loop in LinkedList", "Medium"],
      ["Find starting point of loop", "Medium"], ["Length of loop", "Medium"],
      ["Check palindrome LinkedList", "Medium"], ["Segregate odd & even nodes", "Medium"],
      ["Remove Nth node from end", "Medium"], ["Delete the middle node", "Medium"],
      ["Sort a LinkedList", "Medium"], ["Sort LinkedList of 0s,1s,2s", "Medium"],
      ["Intersection point of Y LinkedList", "Medium"], ["Add 1 to a number (LL)", "Medium"],
      ["Add two numbers as LinkedList", "Medium"], ["Reverse nodes in K group", "Hard"],
      ["Rotate a LinkedList", "Medium"], ["Flatten a LinkedList", "Hard"],
      ["Clone LinkedList with random pointer", "Hard"],
    ]},
    { name: "Step 7 · Recursion", items: [
      ["Recursive implementation of atoi", "Medium"], ["Pow(x, n)", "Medium"],
      ["Count good numbers", "Easy"], ["Sort a stack using recursion", "Medium"],
      ["Reverse a stack using recursion", "Easy"], ["Generate all binary strings", "Medium"],
      ["Generate parentheses", "Medium"], ["Print all subsequences", "Medium"],
      ["Subsequences with sum K", "Medium"], ["Count subsequences with sum K", "Medium"],
      ["Combination Sum", "Medium"], ["Combination Sum II", "Medium"],
      ["Subset Sum I", "Medium"], ["Subset Sum II", "Medium"], ["Combination Sum III", "Medium"],
      ["Letter combinations of phone number", "Medium"], ["Palindrome partitioning", "Medium"],
      ["Word search", "Medium"], ["N-Queens", "Hard"], ["Rat in a maze", "Hard"],
      ["M-coloring problem", "Hard"], ["Sudoku solver", "Hard"], ["Expression add operators", "Hard"],
    ]},
    { name: "Step 8 · Bit Manipulation", items: [
      ["Introduction to bit operators", "Easy"], ["Check if Kth bit is set", "Easy"],
      ["Check odd or even", "Easy"], ["Check power of 2", "Easy"], ["Count set bits", "Easy"],
      ["Set/clear/toggle Kth bit", "Easy"], ["Remove last set bit", "Easy"],
      ["Swap two numbers", "Easy"], ["Divide two integers without / or *", "Medium"],
      ["Single number II", "Medium"], ["Single number III", "Medium"],
      ["XOR of numbers in range L to R", "Medium"], ["Print all subsets (bitmasking)", "Medium"],
      ["Find prime factors", "Medium"], ["All divisors of a number", "Easy"],
      ["Sieve of Eratosthenes", "Medium"], ["Power(n, x)", "Medium"],
    ]},
    { name: "Step 9 · Stacks & Queues", items: [
      ["Stack using arrays", "Easy"], ["Queue using arrays", "Easy"],
      ["Stack using queue", "Medium"], ["Queue using stack", "Medium"],
      ["Stack using LinkedList", "Easy"], ["Queue using LinkedList", "Medium"],
      ["Balanced parentheses", "Medium"], ["Implement Min Stack", "Medium"],
      ["Infix to Postfix", "Medium"], ["Prefix to Infix", "Medium"], ["Prefix to Postfix", "Medium"],
      ["Postfix to Infix", "Medium"], ["Postfix to Prefix", "Medium"], ["Infix to Prefix", "Medium"],
      ["Next Greater Element", "Medium"], ["Next Greater Element II", "Medium"],
      ["Next Smaller Element", "Medium"], ["Trapping rainwater", "Hard"],
      ["Sum of subarray minimums", "Medium"], ["Asteroid collision", "Medium"],
      ["Sum of subarray ranges", "Medium"], ["Remove K digits", "Medium"],
      ["Largest rectangle in histogram", "Hard"], ["Maximal rectangle", "Hard"],
      ["Sliding window maximum", "Hard"], ["Stock span problem", "Medium"],
      ["The celebrity problem", "Hard"], ["LRU cache", "Hard"], ["LFU cache", "Hard"],
    ]},
    { name: "Step 10 · Sliding Window & Two Pointer", items: [
      ["Longest substring without repeating chars", "Medium"],
      ["Max consecutive ones III", "Medium"], ["Fruit into baskets", "Medium"],
      ["Longest repeating character replacement", "Medium"], ["Binary subarray with sum", "Medium"],
      ["Count number of nice subarrays", "Medium"],
      ["Number of substrings containing all 3 chars", "Medium"],
      ["Max points from cards", "Medium"], ["Longest substring with at most K distinct", "Medium"],
      ["Subarray with K different integers", "Hard"], ["Minimum window substring", "Hard"],
      ["Minimum window subsequence", "Hard"],
    ]},
    { name: "Step 11 · Heaps", items: [
      ["Introduction to Priority Queue / Heaps", "Easy"], ["Min-heap & Max-heap implementation", "Medium"],
      ["Check if array is min-heap", "Easy"], ["Convert min-heap to max-heap", "Easy"],
      ["Kth largest element", "Medium"], ["Kth smallest element", "Medium"],
      ["Sort a K-sorted array", "Medium"], ["Merge M sorted lists", "Hard"],
      ["Replace elements by rank in array", "Medium"], ["Task scheduler", "Medium"],
      ["Hands of straights", "Medium"], ["Design Twitter", "Medium"],
      ["Connect N ropes with min cost", "Medium"], ["Kth largest element in a stream", "Easy"],
      ["Maximum sum combination", "Medium"], ["Find median from data stream", "Hard"],
      ["Top K frequent elements", "Medium"],
    ]},
    { name: "Step 12 · Greedy Algorithms", items: [
      ["Assign cookies", "Easy"], ["Fractional knapsack", "Medium"],
      ["Greedy algorithm to find min coins", "Medium"], ["Lemonade change", "Easy"],
      ["Valid parenthesis string", "Medium"], ["N meetings in one room", "Medium"],
      ["Jump game", "Medium"], ["Jump game II", "Medium"], ["Minimum platforms", "Medium"],
      ["Job sequencing problem", "Medium"], ["Candy", "Hard"],
      ["Shortest Job First (SJF)", "Easy"], ["Insert interval", "Medium"],
      ["Merge intervals", "Medium"], ["Non-overlapping intervals", "Medium"],
    ]},
    { name: "Step 13 · Binary Trees", items: [
      ["Introduction to Trees", "Easy"], ["BFS - Level order traversal", "Easy"],
      ["Preorder traversal", "Easy"], ["Inorder traversal", "Easy"], ["Postorder traversal", "Easy"],
      ["All 3 traversals in one iteration", "Medium"], ["Height of binary tree", "Medium"],
      ["Check balanced binary tree", "Medium"], ["Diameter of binary tree", "Medium"],
      ["Maximum path sum", "Hard"], ["Check identical trees", "Medium"],
      ["Zig-zag / spiral traversal", "Medium"], ["Boundary traversal", "Medium"],
      ["Vertical order traversal", "Medium"], ["Top view of binary tree", "Medium"],
      ["Bottom view of binary tree", "Medium"], ["Right/Left view", "Medium"],
      ["Symmetric binary tree", "Medium"], ["Root to node path", "Medium"],
      ["LCA in binary tree", "Medium"], ["Maximum width of binary tree", "Medium"],
      ["Children sum property", "Hard"], ["Nodes at distance K", "Medium"],
      ["Minimum time to burn tree", "Hard"], ["Count nodes in complete tree", "Medium"],
      ["Construct tree from inorder & preorder", "Hard"],
      ["Construct tree from inorder & postorder", "Hard"],
      ["Serialize and deserialize tree", "Hard"], ["Morris inorder traversal", "Medium"],
      ["Flatten binary tree to LinkedList", "Hard"],
    ]},
    { name: "Step 14 · Binary Search Trees", items: [
      ["Introduction to BST", "Easy"], ["Search in a BST", "Easy"],
      ["Min/Max in BST", "Easy"], ["Ceil in a BST", "Easy"], ["Floor in a BST", "Easy"],
      ["Insert a node in BST", "Medium"], ["Delete a node in BST", "Medium"],
      ["Kth smallest/largest in BST", "Medium"], ["Validate a BST", "Medium"],
      ["LCA in BST", "Medium"], ["Construct BST from preorder", "Medium"],
      ["Inorder successor/predecessor", "Medium"], ["BST iterator", "Medium"],
      ["Two sum in BST", "Medium"], ["Recover BST (correct swapped nodes)", "Hard"],
      ["Largest BST in binary tree", "Hard"],
    ]},
    { name: "Step 15 · Graphs", items: [
      ["Graph representation & introduction", "Easy"], ["Connected components", "Medium"],
      ["BFS traversal", "Medium"], ["DFS traversal", "Medium"], ["Number of provinces", "Medium"],
      ["Rotten oranges", "Medium"], ["Flood fill", "Medium"],
      ["Detect cycle (undirected) BFS", "Medium"], ["Detect cycle (undirected) DFS", "Medium"],
      ["0/1 matrix (distance of nearest cell)", "Medium"], ["Surrounded regions", "Medium"],
      ["Number of enclaves", "Medium"], ["Word ladder I", "Hard"], ["Word ladder II", "Hard"],
      ["Number of distinct islands", "Medium"], ["Bipartite graph", "Medium"],
      ["Detect cycle in directed graph", "Hard"], ["Topological sort (Kahn's BFS)", "Medium"],
      ["Topological sort (DFS)", "Medium"], ["Course schedule I & II", "Medium"],
      ["Find eventual safe states", "Medium"], ["Alien dictionary", "Hard"],
      ["Shortest path in DAG", "Medium"], ["Shortest path in undirected graph", "Medium"],
      ["Dijkstra's algorithm", "Medium"], ["Shortest distance in binary maze", "Medium"],
      ["Path with minimum effort", "Medium"], ["Cheapest flights within K stops", "Medium"],
      ["Network delay time", "Medium"], ["Number of ways to arrive at destination", "Hard"],
      ["Bellman-Ford algorithm", "Hard"], ["Floyd-Warshall algorithm", "Hard"],
      ["Minimum spanning tree (intro)", "Hard"], ["Prim's algorithm", "Hard"],
      ["Disjoint Set (Union by Rank & Path Compression)", "Hard"], ["Kruskal's algorithm", "Hard"],
      ["Number of operations to make network connected", "Hard"], ["Accounts merge", "Hard"],
      ["Making a large island", "Hard"], ["Bridges in graph (Tarjan)", "Hard"],
      ["Articulation point", "Hard"], ["Kosaraju's algorithm (SCC)", "Hard"],
    ]},
    { name: "Step 16 · Dynamic Programming", items: [
      ["Introduction to DP (memo/tab/space opt)", "Easy"], ["Climbing stairs", "Easy"],
      ["Frog jump", "Medium"], ["Frog jump with K distances", "Medium"],
      ["Maximum sum of non-adjacent elements", "Medium"], ["House robber II", "Medium"],
      ["Ninja's training", "Medium"], ["Grid unique paths", "Medium"],
      ["Unique paths II (with obstacles)", "Medium"], ["Minimum path sum in grid", "Medium"],
      ["Triangle - min path sum", "Medium"], ["Min/Max falling path sum", "Medium"],
      ["Cherry pickup II", "Hard"], ["Subset sum equal to target", "Medium"],
      ["Partition equal subset sum", "Medium"], ["Partition set into two min difference", "Hard"],
      ["Count subsets with sum K", "Medium"], ["Count partitions with given difference", "Hard"],
      ["0/1 Knapsack", "Medium"], ["Minimum coins", "Medium"], ["Target sum", "Medium"],
      ["Coin change II", "Medium"], ["Unbounded knapsack", "Medium"], ["Rod cutting", "Medium"],
      ["Longest common subsequence", "Medium"], ["Print LCS", "Hard"],
      ["Longest common substring", "Medium"], ["Longest palindromic subsequence", "Medium"],
      ["Min insertions to make palindrome", "Hard"], ["Min insert/delete to convert string", "Medium"],
      ["Shortest common supersequence", "Hard"], ["Distinct subsequences", "Hard"],
      ["Edit distance", "Hard"], ["Wildcard matching", "Hard"],
      ["Best time to buy & sell stock II", "Medium"], ["Buy & sell stock III", "Hard"],
      ["Buy & sell stock IV", "Hard"], ["Buy & sell with cooldown", "Medium"],
      ["Buy & sell with transaction fee", "Medium"], ["Longest increasing subsequence", "Medium"],
      ["Print LIS", "Hard"], ["LIS using binary search", "Medium"],
      ["Largest divisible subset", "Medium"], ["Longest string chain", "Medium"],
      ["Longest bitonic subsequence", "Hard"], ["Number of LIS", "Medium"],
      ["Matrix chain multiplication", "Hard"], ["Min cost to cut the stick", "Hard"],
      ["Burst balloons", "Hard"], ["Evaluate boolean expression to true", "Hard"],
      ["Palindrome partitioning II", "Hard"], ["Partition array for maximum sum", "Medium"],
      ["Maximal rectangle of 1s", "Hard"], ["Count square submatrices with all 1s", "Medium"],
    ]},
    { name: "Step 17 · Tries", items: [
      ["Implement Trie (Insert/Search/StartsWith)", "Medium"], ["Implement Trie II (prefix count)", "Medium"],
      ["Longest word with all prefixes", "Medium"], ["Number of distinct substrings", "Hard"],
      ["Maximum XOR of two numbers in array", "Hard"], ["Maximum XOR with element from array", "Hard"],
    ]},
    { name: "Step 18 · Strings (Advanced)", items: [
      ["Minimum chars to add for palindrome", "Hard"], ["Longest palindromic substring (revisit)", "Hard"],
      ["Count distinct substrings", "Hard"], ["KMP algorithm / LPS array", "Hard"],
      ["Rabin-Karp algorithm", "Hard"], ["Z-function", "Hard"],
      ["Shortest palindrome", "Hard"], ["Longest happy prefix", "Hard"],
      ["Count palindromic subsequences", "Hard"],
    ]},
  ],
};
